on:
  push:
    branches: [main]
    #paths:
    #  - "*-client/**"

jobs:
  python:
    name: Test Python
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.6"
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          cd python-client
          pip3 install -r requirements.txt
          pip3 install -r test-requirements.txt
      - name: Test package
        run: |
          pytest --cov=libretime.api
  php:
    name: Test PHP
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - "7.3"
          - "7.4"
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
      - name: Get composer cache directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: Install dependencies
        run: |
          cd php-client
          composer install
      - name: Test package
        run: |
          vendor/bin/phpunit
  javascript:
    name: Test Javascript
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - "10.x"
          - "12.x"
          - "14.x"
          - "15.x"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          php-version: ${{ matrix.node-version }}
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: |
          cd javascript-client
          npm install
          npm run build --if-present
      - name: Test package
        run: |
          npm test
